### ISSUE TITLE
Horizontal Scrolling Momentum

### ISSUE THREAD

**Issue by bawigga** [psequel/psequel-issues#13] opened 2015-02-05 21:17 UTC
As mentioned in #4 there seems to be some issues with horizontal scrolling on large tables. It seems if you attempt to perform a horizontal scroll but aren't on a near perfectly horizontal axis (I'm swiping on a trackpad) the scroll is stopped.

**Comment by psequel** [comment] 2015-03-21 00:55
I was able to reproduce this bug in the past. However, today I found that I'm unable to reproduce it (with my MBP's built-in touchpad or a magic mouse). Maybe a OS X version related problem? I'm using OS X 10.10.2.

**Comment by ivancamilov** [comment] 2015-05-20 05:48
sometimes I'm able to replicate this for vertical scrolling as well when I have a large enough dataset. I'm using OSX 10.10.3 and have PSequel 1.1.1.

**Comment by ghecho** [comment] 2015-05-26 02:32
I am able to reproduce this bug in PSequel Version 1 (1.1.1), Yosemite 10.10.3 and a table with 67 columns

**Comment by psequel** [comment] 2015-06-26 06:03
Fixed in v1.1.2.

**Closed by psequel** 2015-06-26 06:03 UTC
Labels: bug

**Comment by bawigga** [comment] 2015-06-29 19:31
This is SO much better. Thank you!
