### ISSUE TITLE
Can't update to v1.0.11

### ISSUE THREAD

**Issue by briankracoff** [psequel/psequel-issues#31] opened 2015-03-27 16:06 UTC
I'm on v1.0.10. I went to "Check for Update" and it found an update. Installed the update and restarted the app but I'm still on v1.0.10. Went to "Check for Update" again and it still says there's an update.

**Comment by psequel** [comment] 2015-03-27 18:21
I'm unable to reproduce this. You could try deleting ~/Library/Application Support/com.psequel.PSequel.ShipIt.

**Comment by briankracoff** [comment] 2015-03-27 18:27
Tried that and it didn't work. I just redownloaded the app.

**Comment by psequel** [comment] 2015-03-27 19:12
Did you have any problem updating to v1.0.10 from an earlier version?

**Comment by briankracoff** [comment] 2015-03-27 19:19
Not that I can remember

**Comment by psequel** [comment] 2015-03-27 19:25
Then I have no idea why it's not working for you this time. From the web server logs, many people have tried to upgrade. Let's wait and see if other people report failures here.

**Comment by psequel** [comment] 2015-04-01 23:12
Close this issue for now. Please reply to this post if you have the same issue.

**Closed by psequel** 2015-04-01 23:12 UTC
