### ISSUE TITLE
Can I contribute to the private repo?

### ISSUE THREAD

**Issue by JHKennedy4** [psequel/psequel-issues#37] opened 2015-04-13 02:09 UTC
I use psequel everyday, and there are a few bugs that I'd love to take a crack at for my own sanity (horizontal scrolling for example). Would love to contribute whether or not this is public.

**Comment by psequel** [comment] 2015-04-13 04:52
I'm unable to reproduce the "horizontal scrolling" bug after upgrading OS X to 10.10.2 on my two Macbooks

**Comment by JHKennedy4** [comment] 2015-04-13 16:54
I am still able to reproduce it. Horizontal scroll doesn't carry momentum
properly, stops short. OS X 10.10.2, psequel 1.1.1

May just be due to the rebound effect occurring on every horizontal scroll
motion creating the effect of getting stuck, rather than running out of
momentum.

In either case, I'd love to be able to help out with the project. Whether
on this particular bug or others.

**Comment by ksteensma** [comment] 2015-05-22 16:37
Yep, this is definitely an issue for me as well.  There's a delay as if the app seems to be fetching more data.

**Comment by psequel** [comment] 2015-06-26 06:04
Horizontal scrolling is fixed in v1.1.2.

**Closed by psequel** 2015-06-26 06:04 UTC
